# Generated by Django 2.1.3 on 2018-11-05 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z ]+$', message="Invalid Course Name, Can't Be Empty or Whitespace")], verbose_name='Course Name')),
                ('code', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Too Long Course Code')], verbose_name='Course Code')),
                ('details', models.TextField(blank=True, max_length=512, null=True, verbose_name='Course Details')),
            ],
        ),
    ]
