# Generated by Django 2.1.3 on 2018-11-05 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z ]+$', message="Invalid Course Name, Can't Be Empty or Whitespace")], verbose_name='Chapter Name')),
                ('details', models.TextField(blank=True, max_length=512, null=True, verbose_name='Chapter Details')),
                ('state', models.CharField(choices=[('F', 'FAIL'), ('S', 'success'), ('N', 'notyet')], default='N', max_length=5, verbose_name='State of Exam')),
                ('course_id', models.ForeignKey(on_delete='CASCADE', to='courses.Course')),
            ],
        ),
    ]
