# Generated by Django 2.1.3 on 2018-11-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course_id',
            new_name='course',
        ),
    ]
