# Generated by Django 2.1.3 on 2018-11-05 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_chapter_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z 1-9:]+$', message="Invalid Course Name, Can't Be Empty or Whitespace")], verbose_name='Question')),
                ('is_right', models.BooleanField(default=False, verbose_name='Is the right choice')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z 1-9:]+$', message="Invalid Course Name, Can't Be Empty or Whitespace")], verbose_name='Question')),
                ('objective', models.CharField(choices=[('REMINDING', 'Measure Question'), ('UNDERSTANDING', 'Measure Understanding'), ('CREATIVITY', 'Measure Creativity')], default='REMINDING', max_length=15, verbose_name='Objective of Question')),
                ('difficulty', models.CharField(choices=[('DIFFICULT', 'Difficult Question'), ('EASY', 'Easy Question')], default='EASY', max_length=15, verbose_name='Difficulty of Question')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3, 'Cannot exceed 999 value ')], verbose_name='Question Score')),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Question'),
        ),
    ]
