# Generated by Django 2.1.3 on 2018-11-05 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20181105_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z 1-9:]+$', message="Invalid Chapter Name, Can't Be Empty or Whitespace")], verbose_name='Chapter Name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z 1-9:]+$', message="Invalid Choice Can't Be Empty or Whitespace")], verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z 1-9:?!]+$', message="Invalid Question Content, Can't Be Empty or Whitespace")], verbose_name='Question'),
        ),
    ]
