# Generated by Django 2.1.3 on 2018-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181105_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='state',
            field=models.CharField(choices=[('F', 'FAIL'), ('S', 'success'), ('N', 'Not Done Yet')], default='N', max_length=1, verbose_name='State of Exam'),
        ),
    ]
